Main/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import add_friend.urls as add_friend
import stat_dash.urls as stat_dash
import update_status.urls as update_status
import halaman_profile.urls as halaman_profile
import landing_page.urls as landing_page
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^add-friend/', include(add_friend, namespace='add-friend')),
    url(r'^dashboard/', include(stat_dash, namespace='dashboard')),
    url(r'^profile/', include(halaman_profile, namespace='profile')),
    url(r'^update-status/', include(update_status, namespace='update-status')),
    url(r'^landing-page/', include(landing_page, namespace='landing-page')),
    url(r'^$', RedirectView.as_view(url='landing-page/', permanent=True), name='$'),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add', add_friend, name='add_friend'),
    ]

halaman_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

landing_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

stat_dash/urls.py
from django.conf.urls import url
from stat_dash.views import index

urlpatterns = [
    url(r'^$', index, name='index')
]

update_status/urls.py
from django.conf.urls import url
from .views import delete_status, add_status, index

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id>[0-9999]+)/$', delete_status, name='delete_status'),
]

add_friend/models.py
from django.db import models


class Friend(models.Model):
    name = models.CharField(max_length=27)
    url = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'name: {}, url: {} added on {}'.format(self.name, self.url, self.created_date)

halaman_profile/models.py
# Create your models here.
from django.db import models


class Profile(models.Model):
    name = 'Team 7'
    birthday = 'Nov 22'
    gender = 'Male'
    description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
    email = 'dpraharsa@yahoo.com'

landing_page/models.py
from django.db import models

# Create your models here.

stat_dash/models.py
from django.db import models

update_status/models.py
from django.db import models

class Status(models.Model):
    name = models.CharField(max_length=27)
    message = models.TextField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

add_friend/forms.py
from django import forms
from django.core.validators import RegexValidator


class Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi url yang valid',
    }
    name_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder': 'Nama...'
    }
    url_attrs = {
        'type': 'text',
        'class': 'todo-form-textarea',
        'placeholder': 'contoh: https://x.herokuapp.com/'
    }

    name = forms.CharField(label='Nama ', required=True, max_length=40,
                           widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='url ', required=True, validators=[RegexValidator(r'herokuapp.com/$')], error_messages=error_messages,
                         widget=forms.URLInput(attrs=url_attrs))

halaman_profile/forms.py
forms.py

update_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    message = forms.CharField(label='', widget=forms.Textarea(attrs=attrs), required=True, max_length=300)

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

response = {}


def index(request):
    response['author'] = 'Kelompok 7 PPW-F'
    response['friend_form'] = Friend_Form
    response['friends'] = Friend.objects.all()
    return render(request, 'add_friend_page.html', response)


def add_friend(request):
    form = Friend_Form(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        friends = Friend(name=response['name'], url=response['url'])
        friends.save()
        response['error'] = False
        return HttpResponseRedirect('/add-friend/')
    else:
        response['error'] = True
        return render (request,'add_friend_page.html',response)

halaman_profile/views.py
from django.shortcuts import render
from .models import Profile
response = {}
keahlian = ['ngoding', 'adbis', 'main game', 'PPW SERU']


def index(request):
    response['author'] = 'Kelompok 7 PPW-F'
    response['name'] = Profile.name
    response['birthday'] = Profile.birthday
    response['email'] = Profile.email
    response['gender'] = Profile.gender
    response['expertise'] = keahlian
    response['description'] = Profile.description
    return render(request, 'profile.html', response)

# Create your views here.

landing_page/views.py
from django.shortcuts import render
from halaman_profile.models import Profile

# Create your views here.
def index(request):
    response={'author':'Kelompok 7 PPW-F', 'name' : Profile.name}
    html = 'LandingPage.html'
    return render(request, html, response)

stat_dash/views.py
from django.shortcuts import render
from add_friend.models import Friend
from update_status.models import Status
from halaman_profile.models import Profile

# Create your views here.

response = {}


def index(request):
    response['latest'] = ''
    response['date'] = ''
    if Status.objects.all().count() > 0:
        latestStatus = Status.objects.all().order_by('-created_date')[0]
        response['latest'] = latestStatus.message
        response['date'] = latestStatus.created_date
    response['author'] = 'Kelompok 7 PPW-F'
    response['name'] = Profile.name
    response['friend'] = Friend.objects.all().count()
    response['feed'] = Status.objects.all().count()
    return render(request, 'dashboard.html', response)

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
from halaman_profile.models import Profile

# Create your views here.
response = {'author':'Kelompok 7 PPW-F', 'name' : Profile.name, 'status_form': Status_Form}

def index(request):
    html = 'update_status.html'
    allStatus = Status.objects.all()
    response['allStatus'] = allStatus
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        status = Status(name=response['name'], message=response['message'])
        status.save()
        allStatus = Status.objects.all()
        response['allStatus'] = allStatus
        html = 'update_status.html'
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

def delete_status(request,id):
    status_target = Status.objects.all().get(pk=id)
    status_target.delete()
    return HttpResponseRedirect('/update-status/')

add_friend/templates/add_friend_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <title>CSS</title>
        <link rel="stylesheet" type="text/css" href={% static 'css/add_friend_page.css' %} >
    </head>
    <body>
    <section name="friend">
        <h2 style="color: #39244c; margin-top: 100px">Add Friend</h2>
        <div class="form-container">
            <form id="form" method="POST" action="{% url 'add-friend:add_friend' %}">
                {% csrf_token %}
                {{ friend_form }}
                <br>
                <button type="submit" class="button"><span>Add</span></button>
                <br>
                {% if error %}
                    <p style="color: #ff0007"><strong>Input tidak valid</strong></p>
                {% endif %}
            </form>
        </div>
    </section>
    <h2>Friends</h2>
    <section name="my-list" id="my-list">
        <div class="container">
            <div class="flex">
                {% if friends %}
                    {% for data in friends %}
                        <div class="flex-item">
                            <div class="to-do-list">
                                <div class="to-do-list-title">
                                    {{ data.name }}
                                </div>
                                <div class="to-do-list-date-added">
                                    {{ data.created_date }}
                                </div>
                                <div class="to-do-list-description">
                                    <a href={{ data.url }}>{{ data.url }}</a>
                                </div>
                                <div class="to-do-list-delete">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>
    </body>
    </html>
{% endblock %}

halaman_profile/templates/edit_profile.html
<p>{% extends "base.html" %} {% block content %} {% load staticfiles %} {% load static %}</p>
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap_tag.css' %}" />
<div class="container"><form class="form-horizontal"><fieldset><!-- Form Name --> <legend>My Profile-&gt; user profile-&gt;exhibition</legend> <!-- Text input-->
<div class="form-group"><label class="col-md-4 control-label" for="textinput">Nama</label>
<div class="col-md-4"><input id="textinput" class="form-control input-md" name="textinput" type="text" placeholder="name" /></div>
</div>
<div class="control-group"><label class="control-label" for="selectbasic">Gender</label>
<div class="controls"><select id="selectbasic" class="input-xlarge" name="selectbasic">
<option>Select</option>
<option>Male</option>
<option>Female</option>
<option>Other</option>
</select></div>
</div>
<!-- Text input-->
<div class="form-group"><label class="col-md-4 control-label" for="textinput">date</label>
<div class="col-md-4"><input id="textinput" class="form-control input-md" name="textinput" type="text" placeholder="date attended" /></div>
</div>
<!-- Text input-->
<div class="form-group"><label class="col-md-4 control-label" for="textinput">Expertise</label><br>
 {% for data in expertise %}
<input type="checkbox" name="vehicle" value="Bike">{{data}}<br>
{% endfor %}
 </div>
</div>
<!-- Select Basic -->
<div class="form-group"><label class="col-md-4 control-label" for="selectbasic">country</label>
<div class="col-md-4"><select id="selectbasic" class="form-control" name="selectbasic">
<option value="1">1</option>
<option value="2">2</option>
</select></div>
</div>
<!-- Textarea -->
<div class="form-group"><label class="col-md-4 control-label" for="textarea">trade show introduction</label>
<div class="col-md-4"><textarea id="textarea" class="form-control" name="textarea">trade show introduction</textarea></div>
</div>
<!-- File Button -->
<div class="form-group"><label class="col-md-4 control-label" for="filebutton">upload photo</label>
<div class="col-md-4"><input id="filebutton" class="input-file" name="filebutton" type="file" /></div>
</div>
<!-- Button -->
<div class="form-group"><label class="col-md-4 control-label" for="singlebutton"></label>
<div class="col-md-4"><button id="singlebutton" class="btn btn-primary" name="singlebutton">submit</button></div>
</div>
</fieldset></form></div>

halaman_profile/templates/profile.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% load static %}
<h1 style="text-align: center;">a</h1>
<div style="text-align: center;"><img class="img-circle" style="border-radius: 50%; height: 200px; width: 200px" src="https://vignette2.wikia.nocookie.net/naruto/images/5/50/Team_Kakashi.png/revision/latest?cb=20161219035928"/></div>
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />
<hr />
<section>
<h2 style="font-weight: bold;" align="center"> Profile {{name}}</h2>
</section>
<hr />
<section style="margin: auto;" id='table'>
<table style="width: 547px; height: 122px; text-align: left;" align="center">
<tbody>
<tr>
<td style="width: 169.2px;">Birthday</td>
<td style="width: 356.8px;">{{ birthday }}</td>
</tr>
<tr>
<td style="width: 169.2px;">Gender</td>
<td style="width: 356.8px;">{{ gender }}</td>
</tr>
<tr>
<td style="width: 169.2px;">Expertise</td>
<td style="width: 356.8px;">{% for data in expertise %}
<button class="button" style="vertical-align:middle"><span>{{data}}</span>
{% endfor %}
</tr>
<tr>
</td>
<td style="width: 169.2px;">Description</td>
<td style="width: 356.8px;">{{ description }}</td>
</tr>
<tr>
<td style="width: 169.2px;">Email</td>
<td style="width: 356.8px;">{{ email }}</td>
</tr>
</tbody>
</table>
</section>
<hr />
<p>{% endblock %}</p>

stat_dash/templates/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <title>CSS</title>
        <link rel="stylesheet" type="text/css" href={% static 'css/dashboard.css' %}>
    </head>
    <body>
    <section style="text-align: center; margin: auto;">
        <img alt="my image" src='https://vignette.wikia.nocookie.net/naruto/images/5/50/Team_Kakashi.png/revision/latest?cb=20161219035928'
             style="width: 300px;height: 300px; margin-top: 75px; border-radius: 50%;">
    </section>
    <section style="text-align: center; margin: auto">
        <h4 style="text-align: center;">{{ name }}</h4>
        <table class="table-hover">
            <thead>
            <tr>
                <th style="width: 100px">

                    <img src="https://media-public.canva.com/MAAWVHfQp6c/1/thumbnail.png" class="icon" align="left">
                    {{ friend }}
                </th>
                <th>
                    <img src="https://media-public.canva.com/MABIMfSXGQg/1/thumbnail.png" class="icon" align="left">
                    {{ feed }}
                </th>
            </tr>
            </thead>
        </table>
    </section>
    <hr/>
    <section>
        {% if latest != '' %}
            <div class="card">
                <p><img class= "rounded-circle" src='https://vignette.wikia.nocookie.net/naruto/images/5/50/Team_Kakashi.png/revision/latest?cb=20161219035928'
                        align="left">Latest Post: '{{ latest }}' on {{ date }} </p>
            </div>
        {% endif %}
    </section>
    </body>
    </html>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lingin</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body style="min-height: 100%; background: #ffffff;  /* fallback for old browsers */
background: -webkit-linear-gradient(to bottom right,rgba(255, 165, 150, 0.5), rgba(0, 228, 255, 0.35));  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to bottom right, rgba(255, 165, 150, 0.5), rgba(0, 228, 255, 0.35)); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */">
<header>
    {% block header %}
        {% include "partials/header.html" %}
    {% endblock %}
</header>
<div class="container" style="margin-top: 20px; margin-bottom: 50px;min-height: 100vh">
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
<footer>
    {% block footer %}
        {% include "partials/footer.html" %}
    {% endblock %}
</footer>
</html>

templates/partials/footer.html
{% block content %}
<p style="margin-top:10px; text-align: center;">&copy; {{author}}</p>
{% endblock %}

templates/partials/header.html
<style>
    .bg-light {
        position: fixed;
        width: 100%;
        top: 0;
        z-index: 100;
        box-shadow: 0 0 10px 0px rgba(0, 0, 0, 0.1);
    }

    .navbar-brand, #navbarNav {
        margin-left: 10px;
        margin-right: 10px;
        transition: 0.5s all ease;
    }

    .navbar-brand {
        color: #77bceb !important;
        font-family: "Pacifico", cursive;
        letter-spacing: 2px;
        margin-top: -5px;
        font-size: 20pt;
        text-decoration: none;
        display: inline-block;
        text-align: center;
    }

    .nav-link {
        transition: all 0.2s linear;
        display: inline;
        text-decoration: none;
        font-weight: 600;
        padding-bottom: 5px;
        background: linear-gradient(to right, #007DD1 0%, rgb(131, 190, 219) 98%);
        background-size: 0px 2px;
        background-repeat: no-repeat;
        background-position: left 85%;

    }

    .nav-link:hover {
        background-size: 100% 2px;
    }
</style>

<div class="container-fullwidth">
    <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light ">
        <a class="navbar-brand" href="/landing-page/">Lingin</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-right" id="navbarNav"
             style="flex-direction: row-reverse;padding: 5px">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/update-status/">Status</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/profile/">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/add-friend/">Friends</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/dashboard/">Stats</a>
                </li>
            </ul>
        </div>
    </nav>
</div>

update_status/templates/update_status.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
</head>

    <section name="form">
        <h2 style="margin-top: 100px">Update Status</h2>
        <form id="form" method="POST" action="{% url 'update-status:add_status' %}">
            {% csrf_token %}
            {{ status_form }}
            <br>
            <button type="submit" class="btn btn-default"><span>Post</span></button>
        </form>
        <br>
    </section>

    <section name="status history">
        <div class="flex">
            {% for i in allStatus reversed %}
            <div class="flex-item">
                <div class="list-status-photo-status">
                    <img class = "avatar_image" id="status-photo" src="https://vignette2.wikia.nocookie.net/naruto/images/5/50/Team_Kakashi.png/revision/latest?cb=20161219035928">
                </div>
                <div class="list-status">
                    <b class="author_name"> {{i.name}} </b>
                    <p class="status_message"> {{i.message}} </p>
                    <p class="created_time"> {{i.created_date}} </p>
                </div>
                <div class="to-do-list-delete">
                        <div class="to-do-list-delete-button" data-id="{{i.id}}">Delete</div>
                    </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
          $(".to-do-list-delete-button").click(function() {
          var id = $(this).data('id');
          location.href="delete_status/" + id;
        });
      </script>
{% endblock %}